# Generated by Django 6.0.5 on 2026-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_days',
            field=models.IntegerField(default=7, help_text='Strict duration of the tour in days'),
        ),
    ]
