# Generated by Django 6.0.5 on 2026-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_booking_is_paid_booking_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
