# Generated by Django 6.0.5 on 2026-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
